[package]
name = "solana-loader-v3-interface"
description = "Solana loader V3 interface."
documentation = "https://docs.rs/solana-loader-v3-interface"
version = "7.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-instruction-error = { workspace = true }
solana-pubkey = { workspace = true, features = ["curve25519"] }
solana-sdk-ids = { workspace = true }

[lints]
workspace = true
